plot_setup: ${.plot_setup_map.${vs_type}}

plot_setup_map: 
  e: 
    public_plots: True 
    inequality_in_title: False # Use inequality in the title to define pt range, instead of an interval
    ylabel: 'Electron mis-id probability'
    xlim: [0.5, 1]
    ratio_yscale: 'log'
    ylim: [2e-5, 1]
    ratio_ylim: [0.5, 40]
  mu:
    public_plots: True 
    inequality_in_title: False 
    ylabel: 'Muon mis-id probability'
    xlim: [0.98, 1]
    ratio_yscale: 'log'
    ylim: [2e-5, 1] # If 1D list, use this range for all plots
    # If 3D list, use different range for each eta/pT bin when plotting. Convention is:
    # [  [ [EtaBin1/PtBin1], [EtaBin1/PtBin2], [EtaBin1/PtBin3] ],
    #    [ [EtaBin2/PtBin1], [EtaBin2/PtBin2], [EtaBin2/PtBin3] ], ...
    ratio_ylim: [  [ [0.5, 20], [0.5, 20], [0.5, 20], [0.5, 20], [0.5, 20], [0.5, 20], [0.5, 20], [0.5, 50], [0.5, 50], [0.5, 50] ],
                   [ [0.5, 20], [0.5, 20], [0.5, 20], [0.5, 20], [0.5, 20], [0.5, 20], [0.5, 20], [0.5, 50], [0.5, 50], [0.5, 50] ],
                   [ [0.5, 20], [0.5, 20], [0.5, 20], [0.5, 20], [0.5, 20], [0.5, 20], [0.5, 20], [0.5, 50], [0.5, 50], [0.5, 50] ],
                   [ [0.5, 20], [0.5, 20], [0.5, 20], [0.5, 20], [0.5, 20], [0.5, 20], [0.5, 20], [0.5, 50], [0.5, 50], [0.5, 50] ]  ]
  jet:
    public_plots: True 
    inequality_in_title: False 
    ylabel: 'Jet mis-id probability'
    ratio_ylabel_pad: 30
    xlim: [0.3, 1]
    # ylim: [  [ [2e-3, 1], [3e-4, 1], [8e-5, 1], [2e-5, 1], [2e-5, 1], [5e-6, 1], [5e-6, 1], [5e-6, 1], [5e-6, 1], [2e-6, 1] ],
    #          [ [2e-3, 1], [3e-4, 1], [8e-5, 1], [2e-5, 1], [2e-5, 1], [5e-6, 1], [5e-6, 1], [5e-6, 1], [5e-6, 1], [2e-6, 1] ],
    #          [ [2e-3, 1], [3e-4, 1], [8e-5, 1], [2e-5, 1], [2e-5, 1], [5e-6, 1], [5e-6, 1], [5e-6, 1], [5e-6, 1], [2e-6, 1] ],
    #          [ [2e-3, 1], [3e-4, 1], [8e-5, 1], [2e-5, 1], [2e-5, 1], [5e-6, 1], [5e-6, 1], [5e-6, 1], [5e-6, 1], [2e-6, 1] ]  ]
    ylim: [  [ [1e-3, 1], [2e-4, 1], [8e-5, 1], [2e-5, 1], [2e-5, 1], [5e-6, 1], [5e-6, 1], [5e-6, 1], [5e-6, 1], [2e-6, 1] ],
             [ [1e-3, 1], [2e-4, 1], [8e-5, 1], [2e-5, 1], [2e-5, 1], [5e-6, 1], [5e-6, 1], [5e-6, 1], [5e-6, 1], [2e-6, 1] ],
             [ [1e-3, 1], [2e-4, 1], [8e-5, 1], [2e-5, 1], [2e-5, 1], [5e-6, 1], [5e-6, 1], [5e-6, 1], [5e-6, 1], [2e-6, 1] ],
             [ [1e-3, 1], [2e-4, 1], [8e-5, 1], [2e-5, 1], [2e-5, 1], [5e-6, 1], [5e-6, 1], [5e-6, 1], [5e-6, 1], [2e-6, 1] ]  ]
    # ratio_ylim: [  [ [0.5, 4.5], [0.5, 6.5], [0.5, 2.5], [0.5, 2.5], [0.5, 2.5], [0.5, 3.5], [0.5, 3.5], [0.5, 3.5], [0.5, 10], [0.5, 10] ],
    #                [ [0.5, 4.5], [0.5, 6.5], [0.5, 2.5], [0.5, 2.5], [0.5, 2.5], [0.5, 3.5], [0.5, 3.5], [0.5, 3.5], [0.5, 10], [0.5, 10] ],
    #                [ [0.5, 4.5], [0.5, 6.5], [0.5, 2.5], [0.5, 2.5], [0.5, 2.5], [0.5, 3.5], [0.5, 3.5], [0.5, 3.5], [0.5, 10], [0.5, 10] ],
    #                [ [0.5, 4.5], [0.5, 6.5], [0.5, 2.5], [0.5, 2.5], [0.5, 2.5], [0.5, 3.5], [0.5, 3.5], [0.5, 3.5], [0.5, 10], [0.5, 10] ]  ]
    ratio_ylim: [  [ [0.99, 1.01], [0.99, 1.01], [0.99, 1.01], [0.99, 1.01], [0.99, 1.01], [0.99, 1.01], [0.99, 1.01], [0.99, 1.01], [0.99, 1.01], [0.99, 1.01] ],
                   [ [0.99, 1.01], [0.99, 1.01], [0.99, 1.01], [0.99, 1.01], [0.99, 1.01], [0.99, 1.01], [0.99, 1.01], [0.99, 1.01], [0.99, 1.01], [0.99, 1.01] ],
                   [ [0.99, 1.01], [0.99, 1.01], [0.99, 1.01], [0.99, 1.01], [0.99, 1.01], [0.99, 1.01], [0.99, 1.01], [0.99, 1.01], [0.99, 1.01], [0.99, 1.01] ],
                   [ [0.99, 1.01], [0.99, 1.01], [0.99, 1.01], [0.99, 1.01], [0.99, 1.01], [0.99, 1.01], [0.99, 1.01], [0.99, 1.01], [0.99, 1.01], [0.99, 1.01] ]  ]
