# basic imports
defaults:
  - discriminator: ???
  - plot_setup
  - selection
  - _self_

# mflow run info
path_to_mlflow: ../Training/python/2018v1/mlruns
run_id: ???

# phase space region
period: '2017 (13 TeV)'
vs_type: jet
sample_tau: HTT
sample_vs_type: TT
pt_bins: [20, 100, 1000]

# selection
read_branches: [ 'tau_pt', 'tau_decayModeFinding', 'tau_decayMode', 'gen_${vs_type}', 'gen_tau', 'tau_charge', 'lepton_gen_charge', 
                  againstElectronMVA6', 'againstMuon3', 'byIsolationMVArun2017v2DBoldDMwLT2017', ]
cuts: ${apply_dm_cuts}

# paths to input tuples used to make predictions
input_taus: 'eval_data/tau_${sample_tau}.h5' 
input_vs_type: 'eval_data/${vs_type}_${sample_vs_type}.h5' 
weights: null

# misc: to be moved elsewhere
wp_name_to_index:
  VVVLoose: 0
  VVLoose: 1
  VLoose: 2
  Loose: 3
  Medium: 4
  Tight: 5
  VTight: 6
  VVTight: 7
  VVVTight: 8