# general
name: DeepTau (Phase 2)
color: black
dashed: False
raw: True

# prediction/target columns
pred_column_prefix: node_
pred_column: ${.pred_column_prefix}${vs_type} # column in internally created pd.DataFrame to be used for metrics computation  
target_column_prefix: node_

# WPs
wp_from: null
