# general 
name: MVA vs. jets (JINST 13 (2018) P10005)
color: green
dashed: False
raw: False

# prediction/target columns
pred_column_prefix: null
pred_column: null
target_column_prefix: node_

# WPs
wp_from: wp_column
wp_column: tau_byIsolationMVArun2017v2DBoldDMwLT2017
working_points: 
  - VVLoose
  - VLoose
  - Loose
  - Medium
  - Tight
  - VTight
  - VVTight

# WP maps
wp_name_to_index:
  VVVLoose: 0
  VVLoose: 1
  VLoose: 2
  Loose: 3
  Medium: 4
  Tight: 5
  VTight: 6
  VVTight: 7
  VVVTight: 8
