var_cfg:
  _target_: functools.partial
  _args_: ["${get_method:__main__.plot_efficiency}"]

  var_name: tau_pt
  var_bins: [ 20, 25, 30, 35, 40, 45, 50, 55, 60, 70, 80, 90, 100, 
              120, 140, 160, 180, 200, 300, 1000 ]

  xlabels: null 
  xerr: null

  xscale: log
  yscale_1: linear
  yscale_2: log

  ylim_1: [0.2, 1]
  ylim_2: [3e-5, 2e-1]

  xtitle: "$p_{T}$ (GeV)"
  ytitle_1: Tau ID efficiency
  ytitle_2: "${vs_type} mis-id probability"
  legend_loc: "lower right"