name: MVA_upd_vs_jet
column: byIsolationMVArun2017v2DBnewDMwLT2017
raw: False
from_tuple: True
color: red
working_points: 
  - ${wp_name_to_index.VVLoose}
  - ${wp_name_to_index.VLoose}
  - ${wp_name_to_index.Loose}
  - ${wp_name_to_index.Medium}
  - ${wp_name_to_index.Tight}
  - ${wp_name_to_index.VTight}
  - ${wp_name_to_index.VVTight}
wp_column: byIsolationMVArun2017v2DBnewDMwLT2017
dashed: True